name: Build Docker Image

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      build:
        description: 'Build the Docker image'
        required: true
        default: true
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PLATFORMS: linux/amd64,linux/arm64
  VERSION: v1.7.10

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    steps:

      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Step 2: Set up QEMU (for multi-architecture builds)
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      # Step 3: Set up Docker Buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}

      # Step 4: Login to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Set lowercase image name
      - name: Set lowercase image name
        id: set_image_name
        run: |
          IMAGE_NAME="ghcr.io/$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')"
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

      # Step 6: Build and Push Multi-Architecture Docker Image
      - name: Build and Push Multi-Arch Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            ${{ steps.set_image_name.outputs.image_name }}:${{ env.VERSION }}
            ${{ steps.set_image_name.outputs.image_name }}:latest
          no-cache: true
          provenance: false